### ISSUE TITLE
Error 355501 when selecting "Guide" from the WiiLink24 website.

### ISSUE THREAD

**Issue by ghost** [WiiLink24/service-issues#11]
1. What service did you run into this issue with?
Wii No Ma (Wii Room)

2. What error did you encounter?
Title says it all. Error 355501 shows up after selecting "Guide" from the WiiLink24 Website from the WiiLink24 Room. (When translated, it says that the Internet was disconnected because of a Communication error. Yada, yada, yada.)

3. How can we reproduce this issue?
Once you're in the Wii Room Main Menu, select `ROOMS` and select the `WiiLink24 Room`. then select the Shiba images that takes you to the website. and select `Guide` to encounter the error. (Maybe `Guide` shouldn't be in the old WiiLink24 website for Wii Room.)

![IMG_2700](https://user-images.githubusercontent.com/56369758/118071808-82fc0780-b376-11eb-8ce5-773c96006c4a.JPG)

**Comment by oscie57** [comment]
Oh yeah, that's because it still points towards wii.guide, which is https and sadly which Wii Room chokes on. Not sure if or how it will be fixed but may in the future. There is some background for ya tho.
