### ISSUE TITLE
Channel issue

### ISSUE THREAD

**Issue by oscie57** [WiiLink24/service-issues#12]
1. What service did you run into this issue with?

Wii no Ma

2. What error did you encounter?

Wii no Ma crashes when exiting a video in 4:3

3. How can we reproduce this issue?

 - Set video mode to 4:3, 480p60Hz
 - Open a video on Wii Room
 - Exit out
Should crash

**Comment by oscie57** [comment]
dead chat

**Comment by spotlightishere** [comment]
This should resolved with re-encoding of videos on the server - not aware of any 4:3 specific crashes at this time.
