### ISSUE TITLE
Run Homebrew SPD

### ISSUE THREAD

**Issue by oscie57** [WiiLink24/service-issues#13]
1. What service did you run into this issue with?
Digicam Print Channel

2. What error did you encounter?
Not an error, but bad string. Says "Please run the SPD app from homebrew channel" when pd.dat is not present.

3. How can we reproduce this issue?
See above

**Comment by noahpistilli** [comment]
Open the issue in the assets please.

**Comment by oscie57** [comment]
i wanted to reopen it ;(
