### ISSUE TITLE
Channel freeze issue

### ISSUE THREAD

**Issue by Chrmel0** [WiiLink24/service-issues#14]
1. What service did you run into this issue with?
Wii no Ma 

2. What error did you encounter?
It froze

3. How can we reproduce this issue?
So I pressed on the first video in the Wiilink24 originals area, watched the trailer, saw it was grubhub and wanted to leave very quickly. Once it loaded I pressed the back button and it freezes on a blank screen, no sound errors.

![16212792056937064828006134041513](https://user-images.githubusercontent.com/77483885/118544437-4f8df400-b74d-11eb-8bc3-41e6f18d5cdc.jpg)

Excuse the crap camera quality, just wanted to show where it was just in case.

**Comment by oscie57** [comment]
the grubhub video is sort of broken

**Comment by spotlightishere** [comment]
Should be good now!
