### ISSUE TITLE
Wii no Ma Channel issue (horn of death)

### ISSUE THREAD

**Issue by kmannumber1** [WiiLink24/service-issues#16]
1. What service did you run into this issue with?
Wii Room

2. What error did you encounter?
The Wii's loud horn sound (AAAAAAAAAAAAA)

3. How can we reproduce this issue?
Load (from SDHC Card)
Open Wiimmfi room
Click on the doge
Close video
Click "Yes"

**Comment by noahpistilli** [comment]
On what region is this? I was unable to reproduce the error on NTSC-U.

**Comment by kmannumber1** [comment]
ntscu, it works now
