### ISSUE TITLE
Beta Wii no Ma issues

### ISSUE THREAD

**Issue by RengeLK** [WiiLink24/service-issues#19]
1. What service did you run into this issue with?
Wii no Ma (beta server)

2. What error did you encounter?
Error code 358404 on some screens in the main room and in most videos
Error code 350400 upon opening shop

3. How can we reproduce this issue?
Wait in main room for the TV to scroll a bit and you should get error code 358404
Same if you go to any video/movie
Opening shop should give you error code 350400 after a while

I am using a PAL Wii if that helps

**Comment by noahpistilli** [comment]
404 errors are not issues. This is because videos are not being served to save us space. 400 should be fixed soon. 

Closing

**Comment by RengeLK** [comment]
400 still occurs
