### ISSUE TITLE
Wii No Ma PAL Issues

### ISSUE THREAD

**Issue by Citrus2705** [WiiLink24/service-issues#3]
PAL is one heckin' buggy mess, here's what's broken

- Running Wii Room at 50Hz causes a pink bar to appear at the bottom of the screen
- Clicking on the poster in the main room causes a PPCHalt 75% of the time (#8)
- Lag when opening the Home Menu
- Random PPCHalts when the camera pans in the main room

**Comment by spotlightishere** [comment]
Closing as these issues have been migrated (WiiLink24/Wii-no-Ma-Patcher#3, WiiLink24/Wii-no-Ma-Patcher#1 etc.) Thank you!
