### ISSUE TITLE
Error when opening Shop

### ISSUE THREAD

**Issue by Citrus2705** [WiiLink24/service-issues#4]
Wii Room errors when loading the shop due to it not existing yet.

**Comment by spotlightishere** [comment]
To tack onto this - some edits made to work around some language issues now crash the shop. This definitely needs further investigation 😅

**Comment by spotlightishere** [comment]
> To tack onto this - some edits made to work around some language issues now crash the shop. This definitely needs further investigation 😅

This should now be resolved. We can most likely add a dummy SWF at this point.

**Comment by noahpistilli** [comment]
Closing as we have a working placeholder swf
