### ISSUE TITLE
Posters in theatre give 404

### ISSUE THREAD

**Issue by noahpistilli** [WiiLink24/service-issues#7]
1. What service did you run into this issue with?
- Wii no Ma NTSC

2. What error did you encounter?

- 358404 - There was an error while viewing this movie

3. How can we reproduce this issue?

- Just click on the poster in the theatre. It does say it will error after all but I just put it here because, issues

**Comment by oscie57** [comment]
Could this be due to no movie being assigned to the poster?

**Comment by noahpistilli** [comment]
Yes but they are encrypted with something that we do not know of.

**Comment by oscie57** [comment]
that is weird

**Comment by noahpistilli** [comment]
Closing as encryption was figured out
